[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/tracker"
  to   = "/.netlify/functions/tracker"
  status = 200
  force  = true

[[redirects]]
  from = "/api/tracker/*"
  to   = "/.netlify/functions/tracker"
  status = 200
  force  = true
